# Lab 3

Labs in general are for you to solve short programming challenges in class. In contrast, homework assignments will involve more challenging and lengthy problems.

Feel free to ask the TAs for help if there is anything you do not understand. The TAs will go through suggested solutions in the last 15 minutes of the lab - typically by solving them in a live demo. 


Please remember to submit the lab on Gradescope. 

### A few points to review
1. NumPy

In [27]:
import numpy as np

**1**. (1 point). Create two lists of 100 random integers in the `range[0, 1000]`. Find all numbers that are shared by the two lists.

In [28]:
list1 = np.random.randint(0,1000,100)
list2 = np.random.randint(0,1000,100)
np.concatenate((list1,list2))

array([ 90, 232, 433, 245, 809, 831, 397, 486, 599, 485, 221, 888, 579,
       681, 821,  59, 825, 602, 289, 280, 842, 920,  83, 379, 291, 183,
       217,  12, 256, 515, 691, 410, 398, 678, 901, 594, 691,  42,  79,
       984,  57, 164, 726, 719, 191, 421, 238, 588, 902, 789, 396, 736,
       250, 431, 688, 158, 459, 585, 756,  41, 730,  86, 255, 334, 512,
       533, 557, 696, 949, 593, 612, 260, 484, 872, 670, 629,  28, 451,
       973, 798, 861, 621, 219, 478, 356, 302, 474, 811, 688, 668, 997,
       585, 489, 265,  40, 174, 208, 732, 313, 176,  87, 157, 691, 746,
       532,  88, 973, 802, 778,  77, 400, 649, 377, 530, 703, 957, 349,
       253, 532, 405, 119, 410, 970, 624,   9, 957, 559, 888, 484, 276,
       418, 402, 650, 871, 957, 800, 221, 680, 192, 212, 684, 516, 559,
       263, 437, 254, 494, 306, 911, 115, 291, 932, 724,  24, 213, 680,
       136, 155, 439, 518, 818, 887,  57, 227, 407, 475, 170, 574, 960,
       987, 300, 147, 725, 936, 387, 692, 669, 596, 729, 366, 72

**2**. (1.5 point). Given a NumPy array `data = np.random.randint(0, 100, size=(10, 10))`, perform the following tasks:

- Create a boolean mask to filter out values greater than 50.
- Use this mask to extract the filtered values.
- Compute the mean of the filtered values.

In [29]:
data = np.random.randint(0, 100, size=(10, 10))
mask = data > 50
filtered_values = data[mask]
mean_filtered_values = np.mean(filtered_values)
mean_filtered_values

75.75675675675676

**3**. (3 points) Basic array manipulation. 

- Generate a random matrix with shape (4,5) with draws from a standard normal distribution
- Find row sums
- Scale so each row has min=0 and max=1 (for a challenge, do this in one line of code)
- Find row sums when you exclude the max in each row

In [30]:
normal_dist = np.random.normal(0, 1, size=(4, 5))
normal_dist

array([[-0.79479678, -1.89029784, -1.16929474,  0.78916651,  0.41017275],
       [-0.49774475, -0.37878456,  1.50007747, -0.13061443,  0.79331147],
       [-0.40376784,  0.6479263 , -0.36294123, -0.80559515,  0.59694752],
       [ 0.00381692, -0.58829299,  0.5594056 ,  1.70214356, -0.37271725]])

In [31]:
row_sums = np.sum(normal_dist, axis=1)
row_sums

array([-2.6550501 ,  1.28624521, -0.3274304 ,  1.30435583])

In [32]:
scaled_normal_dist = (normal_dist - normal_dist.min(axis=1, keepdims=True)) / (normal_dist.max(axis=1, keepdims=True) - normal_dist.min(axis=1, keepdims=True))
scaled_normal_dist

array([[0.40885077, 0.        , 0.26908479, 1.        , 0.85855615],
       [0.        , 0.05954493, 1.        , 0.18376526, 0.64623178],
       [0.2764509 , 1.        , 0.30453897, 0.        , 0.96492739],
       [0.258514  , 0.        , 0.5010829 , 1.        , 0.09411994]])

In [33]:
row_sums_exc = np.sum(scaled_normal_dist - np.max(scaled_normal_dist, axis=1, keepdims=True), axis=1)
row_sums_exc

array([-2.46350829, -3.11045802, -2.45408274, -3.14628316])

**4**. (2 points) Create two NumPy arrays: a 2D array `matrix = np.arange(1, 13).reshape(3, 4)` and a 1D array `vector = np.array([1, 2, 3, 4])`. Perform the following operations using broadcasting:

- Add the vector to each row of the matrix.
- Subtract the vector from each column of the matrix.
- Multiply each element of the matrix by the vector element-wise.
- Return the results of each operation.

In [34]:
matrix = np.arange(1, 13).reshape(3, 4)
vector = np.array([1, 2, 3, 4])

In [35]:
result_add = matrix + vector
result_add

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [36]:
result_subtract = matrix - vector
result_subtract

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [37]:
result_multiply = matrix * vector
result_multiply

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48]])

**5**. (0.5 points). You have two datasets `x = np.array([1, 2, 3, 4, 5])` and `y = np.array([2, 4, 6, 8, 10])`. Compute the Pearson correlation coefficient between `x` and `y`.

Hint: use `np.corrcoef()`

In [38]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

In [39]:
correlation_matrix = np.corrcoef(x,y)
pearson_corr = correlation_matrix[0, 1]
pearson_corr

0.9999999999999999

**6** (2 point). You are working with a dataset of daily sales figures for a retail store over a year. The dataset is represented as a 1D NumPy array `sales_data = [200, 220, 250, 275, 300, 320, 310, 290, 270, 260]`, where each element corresponds to the sales for one day. 

- Compute the cumulative sum of the sales data and print the total sales accumulated up to each day.

- Determine the 25th, 50th, and 75th percentiles (quartiles) of the daily sales data.


In [40]:
sales_data = [200, 220, 250, 275, 300, 320, 310, 290, 270, 260]
sales_data = np.array(sales_data)


In [41]:
cumulative_sales = np.cumsum(sales_data)
quartiles = np.percentile(sales_data, [25, 50, 75])
cumulative_sales, quartiles

(array([ 200,  420,  670,  945, 1245, 1565, 1875, 2165, 2435, 2695]),
 array([252.5, 272.5, 297.5]))