# Homework 1

Please submit the solution to gradescope by 11:59 PM, Sept 12, Thursday.

**Name**: Conor Jones

**PID**: 730665579


In [9]:
import string

## Problem 1 (25 points). 

**1.1** (20 points) Load a text file `file.txt`, clean its content by 


 - removing all punctuation
 - removing extra white spaces
 - transforming the text to lowercase.

Print the cleaned text. 

**1.2** (5 points) Count and print the number of vowels present in the cleaned text

   Example input: `s = "hello world"`

   Example output: `a = 0, e = 1, i = 0, o = 2, u = 0`

In [15]:
def clean_text(text):
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = ' '.join(text.split())
    text = text.lower()
    return text

with open('file.txt') as file:
    original_text = file.read()

cleaned_text = clean_text(original_text)

print(cleaned_text)

development of basic skill set for data analysis in python from obtaining data to data carpentry exploration modeling and communication lectures cover topics such as python programming data cleaning and visualization predictive modeling and elements of machine learning the course will develop fluency in the python language and the standard scientific libraries such as numpy pandas matplotlib and scikitlearn programming analyses in more advanced areas of data science plan to come to every class with your computer and ready to work with others using resources around you is a key component of successful data analysis this includes the internet and people students may not receive credit for both stor 320 and stor 520


In [21]:
vowels = {"a": 0, "e": 0, "i": 0, "o": 0, "u": 0}

for i in cleaned_text:
    if i in vowels:
        vowels[i] += 1

print(f"a = {vowels['a']}, e = {vowels['e']}, i = {vowels['i']}, o = {vowels['o']}, u = {vowels['u']}")


a = 59, e = 58, i = 44, o = 46, u = 19


## Problem 2. (25 point). 

You are organizing information about several data science courses. Given the nested list of tuples `courses = [(101, 'Intro to Data Science'), (201, 'Machine Learning'), (103, 'Data Visualization'), (102, 'Python Programming')]`, perform the following tasks:

**2.1** (5 points) Convert the list of tuples into a dictionary where the course number is the key and the course name is the value.

**2.2** (5 points) Add a new course `(202, 'Deep Learning')` to the dictionary.

**2.3** (5 points) Sort the dictionary based on the course number. 

**2.4** (5 points) Update the dictionary based on the following instruction: `Intro to Data Science` course is combined with `Python Programming` course, called `Intro to Data Science with Python` and the course number is still `101`. Delete the course `Python Programming`.

**2.5** (5 points) Extract the course numbers and course names from the updated dictionary and store them in separate lists, e.g., `[101, 102, 103, 201, 202]`, `['Intro to Data Science with Python', 'Data Visualization',...]`




In [45]:
courses = [(101, 'Intro to Data Science'), (201, 'Machine Learning'), (103, 'Data Visualization'), (102, 'Python Programming')]

data_sci_dict = {}
for i,j in courses:
    data_sci_dict[i] = j

data_sci_dict

{101: 'Intro to Data Science',
 201: 'Machine Learning',
 103: 'Data Visualization',
 102: 'Python Programming'}

In [42]:
data_sci_dict[202] = 'Deep Learning'
data_sci_dict

{101: 'Intro to Data Science',
 201: 'Machine Learning',
 103: 'Data Visualization',
 102: 'Python Programming',
 202: 'Deep Learning'}

In [43]:
keys = list(data_sci_dict.keys())
keys.sort()
data_sci_dict = {i: data_sci_dict[i] for i in keys}
data_sci_dict

{101: 'Intro to Data Science',
 102: 'Python Programming',
 103: 'Data Visualization',
 201: 'Machine Learning',
 202: 'Deep Learning'}

In [44]:
data_sci_dict[101] = "Intro to Data Science with Python"
data_sci_dict.pop(102)
data_sci_dict

{101: 'Intro to Data Science with Python',
 201: 'Machine Learning',
 103: 'Data Visualization',
 202: 'Deep Learning'}

In [50]:
keys_array = []
values_array = []

for key, value in data_sci_dict.items():
    keys_array.append(key)
    values_array.append(value)

print(keys_array)
print(values_array)

[101, 201, 103, 102]
['Intro to Data Science', 'Machine Learning', 'Data Visualization', 'Python Programming']


## Problem 3 (25 points). 

You have two lists of student IDs enrolled in two different data science courses: `course1_ids = [101, 102, 102, 103, 104]` and `course2_ids = [103, 104, 104, 105, 106]`. Perform the following tasks:

**3.1** (5 points) Convert the lists to sets to remove duplicate IDs.

**3.2** (10 points) Find the union and intersection of the two sets to determine which students are in either or both courses.

**3.3** (5 points) Convert the union and intersection sets to sorted lists.

**3.4** (5 points) Create a dictionary where the keys are the student IDs from the union list and the values are True if the student is in both courses, otherwise False.

In [53]:
course1_ids = [101, 102, 102, 103, 104] 
course2_ids = [103, 104, 104, 105, 106]

In [56]:
course1_ids = set(course1_ids)
course2_ids = set(course2_ids)
course1_ids, course2_ids

({101, 102, 103, 104}, {103, 104, 105, 106})

In [61]:
union_ids = course1_ids.union(course2_ids)
intersection_ids = course1_ids.intersection(course2_ids)
union_ids, intersection_ids


({101, 102, 103, 104, 105, 106}, {103, 104})

In [63]:
sorted_union_ids = sorted(union_ids)
sorted_intersection_ids = sorted(intersection_ids)
sorted_union_ids, sorted_intersection_ids

([101, 102, 103, 104, 105, 106], [103, 104])

In [65]:
both_classes = {}
for i in sorted_union_ids:
    if i in sorted_intersection_ids:
        both_classes[i] = True
    else:
        both_classes[i] = False

both_classes

{101: False, 102: False, 103: True, 104: True, 105: False, 106: False}

# Problem 4 (25 points)

**4.1** (5 points) Install a package `sympy`. The `sympy` library is a Python library for symbolic mathematics. You do not have to install this library again if it is already installed. 

**4.2** (10 points) `isprime` function in `sympy` checks if a number is a prime number. For example, `isprime(7)` returns `True`. Based on this function, define a function to find the closest prime number of an integer. For example, if the input is 8, the function should return 7, as it is the closest prime number.



**4.3** (5 points) Treat your PID number at UNC as an integer, and print its closest prime number.

**4.4** (5 points) Given this sequence `[456,983,482,963,749,12,97]`, create a new list where each element is replaced by the closest prime number to that element, using the function defined in **4.2**.



In [67]:
from sympy import isprime

def closest_prime(n):
    lower = n
    while lower > 1 and not isprime(lower):
        lower -= 1
    higher = n
    while not isprime(higher):
        higher += 1
    if abs(n - lower) <= abs(n - higher):
        return lower
    else:
        return higher

In [68]:
pid = 730665579

print(closest_prime(pid))

730665583


In [71]:
sequence = [456,983,482,963,749,12,97]

for index in range(len(sequence)):
    sequence[index] = closest_prime(sequence[index])

sequence

[457, 983, 479, 967, 751, 11, 97]